openapi: 3.0.2
info:
  title: Simwood v3
  description: 'The Simwood Customer API ("Application Programming Interface") is a way for your own back-office systems
    and web sites to seamlessly integrate with Simwood and manage your wholesale telephony account and
    services.'
  termsOfService: https://simwood.com/docs/simwood_aup.pdf
  contact:
    name: Simwood Support Centre
    url: https://support.simwood.com/
  version: 1.0.0
externalDocs:
  description: Simwood Customer API v3 documentation
  url: https://simwood.com/docs/simwood_apiv3.pdf
servers:
  - url: https://api.simwood.com/v3
tags:
  - name: account-management
  - name: outbound-voice
  - name: numbers
  - name: tools
  - name: files
paths:
  /tools/myip:
    get:
      tags: [tools]
      summary: Return your external IP address, as seen by the Simwood API
      operationId: getMyIp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyIp'
  /tools/time:
    get:
      tags: [tools]
      summary: Returns the current timestamp
      operationId: getTime
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Time'
  # /tools/explain:
  /accounts/{account}/type:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [account-management]
      summary: Get your current account type, and limitations
      operationId: getAccountType
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTypeResponse'
  /voice/{account}/outbound:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [outbound-voice]
      summary: List all active outbound trunks
      operationId: getOutboundTrunks
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundTrunksResponse'
  /voice/{account}/outbound/{trunk}:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: trunk
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [outbound-voice]
      summary: Request information of specified trunk
      operationId: getOutboundTrunk
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundTrunk'
    put:
      tags: [outbound-voice]
      summary: Create new trunk or update existing trunk
      operationId: putOutboundTrunk
      security:
        - BasicAuth: []
      requestBody:
        description: Trunk to create or update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OutboundTrunk"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundTrunk'
        400:
          description: Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
    delete:
      tags: [outbound-voice]
      summary: Delete the trunk
      operationId: deleteOutboundTrunk
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
  /voice/{account}/outbound/{trunk}/acl:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: trunk
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [outbound-voice]
      summary: Request information of specified trunk
      operationId: getOutboundAclIps
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundAclIps'
  /voice/{account}/outbound/{trunk}/acl/{ip}:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: trunk
        in: path
        required: true
        schema:
          type: string
      - name: ip
        in: path
        required: true
        schema:
          type: string
    put:
      tags: [outbound-voice]
      summary: Add IP to ACL-based trunk
      operationId: putOutboundAclIp
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
    delete:
      tags: [outbound-voice]
      summary: Remove IP from ACL-based trunk
      operationId: deleteOutboundAclIp
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
  /numbers/{account}/ranges:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [numbers]
      summary: Retrieves a list of all available number ranges, including descriptions
      operationId: getNumberRanges
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NumberRangesResponse'
  /numbers/{account}/available/{tier}/{number}:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: tier
        in: path
        required: true
        schema:
          type: string
      - name: number
        in: path
        required: true
        schema:
          type: integer
    get:
      tags: [numbers]
      summary: Returns 1,10 or 100 numbers available for allocation matching the pattern specified
      operationId: getAvailableNumbers
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableNumbersResponse'
  /numbers/{account}/allocated/all:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
    post:
      tags: [numbers]
      summary: Request a report of all current allocated numbers on account
      operationId: getAllocatedNumbers
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllocatedNumbersResponse'
  /numbers/{account}/allocated/{number}:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: number
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [numbers]
      summary: Return configuration information on allocated number
      operationId: getAllocatedNumber
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllocatedNumberResponse'
        404:
          description: Number not allocated
    put:
      tags: [numbers]
      summary: Allocate an available number to the account
      operationId: putAllocatedNumber
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
        404:
          description: Number not available
    delete:
      tags: [numbers]
      summary: De-configure and irrevocably remove number from account
      operationId: deleteAllocatedNumber
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
        404:
          description: Number not allocated
  # /files/{account}/{hash}:
  #   parameters:
  #     - name: account
  #       in: path
  #       required: true
  #       schema:
  #         type: string
  #     - name: hash
  #       in: path
  #       required: true
  #       schema:
  #         type: string
  #   post:
  #     tags: [files]
  #     summary: Get a file, such as a previously-generated report
  #     operationId: getFile
  #     security:
  #       - BasicAuth: []
  #     responses:
  #       200:
  #         description: Success
  #         content:
  #           application/json:
  #             schema:
  #               ...
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    MyIp:
      type: object
      required: [ip]
      properties:
        ip:
          type: string
    Time:
      type: object
      required: [api, rfc, timestamp]
      properties:
        api:
          type: string
        rfc:
          type: string
        timestamp:
          type: integer
          format: int32
    AccountTypeResponse:
      type: object
      required: [success, data]
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/AccountType'
    AccountType:
      type: object
      required: [account_type]
      properties:
        account_type:
          type: string
        number_limit:
          type: integer
        channel_limit:
          type: integer
        min_prepay:
          type: integer
    OutboundTrunksResponse:
      type: array
      items:
        $ref: '#/components/schemas/OutboundTrunkSummary'
    OutboundTrunkSummary:
      type: object
      required: [trunk, serviceLevel, type]
      properties:
        trunk:
          type: string
        serviceLevel:
          type: string
        type:
          type: string
        # enabled_webrtc
    OutboundTrunk:
      type: object
      properties:
        trunk:
          type: string
        type:
          type: string
        enabled:
          type: string
        enabled_in:
          type: string
        enabled_out:
          type: string
        # enabled_webrtc
        user:
          type: string
        quality:
          type: string
        limit_concurrent_out:
          type: string
        limit_rate_out:
          type: string
        # limit_concurrent_out_international
        # limit_rate_out_international
        # limit_concurrent_out_international_hotspot
        limit_rate_out_international_hotspot:
          type: string
        # limit_concurrent_out_per_number
        # max_cpc
        # max_cpm
        # max_cost
        # max_dur
        # limit_concurrent_in
        # access_codes_enabled
        # dq_enabled
        # cli_default
        cli_force_default:
          type: string
        # nni_default
        # cli_format
        # cli_policy
    OutboundAclIps:
      type: array
      items:
        $ref: '#/components/schemas/OutboundAclIp'
    OutboundAclIp:
      type: object
      properties:
        ip:
          type: string
        timestamp:
          type: string
    NumberRangesResponse:
      type: object
      required: [success, data]
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/NumberRange'
    NumberRange:
      type: object
      required: [id, prefix, sabc, description, chargeband]
      properties:
        id:
          type: string
        prefix:
          type: string
        sabc:
          type: string
        description:
          type: string
        chargeband:
          type: string
    AvailableNumbersResponse:
      type: array
      items:
        $ref: '#/components/schemas/AvailableNumber'
    AvailableNumber:
      type: object
      properties:
        country_code:
          type: string
        number:
          type: string
        block:
          type: string
        bill_class:
          type: string
        SMS:
          type: integer
        recommended_gold_premium:
          type: number
        wholesale_gold_premium:
          type: number
    AllocatedNumbersResponse:
      type: object
      required: [type, account, format, hash, link]
      properties:
        type:
          type: string
        account:
          type: string
        format:
          type: string
        hash:
          type: string
        link:
          type: string
        include_mobile_ott:
          type: boolean
    # AllocatedNumbersFile:
    #   type: array
    #   items:
    #     $ref: '#/components/schemas/AllocatedNumbersFileEntry'
    # AllocatedNumbersFileEntry:
    #   type: object
    #   required: [country_code, number]
    #   properties:
    #     country_code:
    #       type: string
    #     number:
    #       type: string
    #     block:
    #       type: string
    #     type:
    #       type: string
    #     SMS:
    #       type: integer
    #     gold_price:
    #       type: string
    AllocatedNumberResponse:
      type: object
      required: [basic, voice, fax, sms, '999']
      properties:
        basic:
          $ref: '#/components/schemas/AllocatedNumberBasic'
        voice:
          $ref: '#/components/schemas/AllocatedNumberVoice'
        fax:
          $ref: '#/components/schemas/AllocatedNumberFax'
        sms:
          $ref: '#/components/schemas/AllocatedNumberSms'
        '999':
          $ref: '#/components/schemas/AllocatedNumber999'
    AllocatedNumberBasic:
      type: object
      required: [link, country_code, number]
      properties:
        link:
          type: string
        country_code:
          type: string
        number:
          type: string
        block:
          type: string
        bill_class:
          type: string
        SMS:
          type: integer
        # recommend_gold_premium
        # wholesale_gold_premium
    AllocatedNumberVoice:
      type: object
      required: [link]
      properties:
        link:
          type: string
    AllocatedNumberFax:
      type: object
      required: [link]
      properties:
        link:
          type: string
    AllocatedNumberSms:
      type: object
      required: [link]
      properties:
        link:
          type: string
    AllocatedNumber999:
      type: object
      required: [link]
      properties:
        link:
          type: string
    Errors:
      type: object
      required: [errors]
      properties:
        errors:
          type: array
          items:
            type: string
