openapi: 3.0.2
info:
  title: Simwood v3
  description: 'The Simwood Customer API ("Application Programming Interface") is a way for your own back-office systems
    and web sites to seamlessly integrate with Simwood and manage your wholesale telephony account and
    services.'
  termsOfService: https://simwood.com/docs/simwood_aup.pdf
  contact:
    name: Simwood Support Centre
    url: https://support.simwood.com/
  version: 1.0.0
externalDocs:
  description: Simwood Customer API v3 documentation
  url: https://simwood.com/docs/simwood_apiv3.pdf
servers:
  - url: https://api.simwood.com/v3
tags:
  - name: account-management
  - name: tools
paths:
  /tools/myip:
    get:
      tags: [tools]
      summary: Return your external IP address, as seen by the Simwood API
      operationId: getMyIp
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyIp'
  /tools/time:
    get:
      tags: [tools]
      summary: Returns the current timestamp
      operationId: getTime
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Time'
  # /tools/explain:
  /accounts/{account}/type:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [account-management]
      summary: Get your current account type, and limitations
      operationId: getAccountType
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTypeResponse'
  /voice/{account}/outbound:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [outbound-voice]
      summary: List all active outbound trunks
      operationId: getOutboundTrunks
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundTrunksResponse'
  /voice/{account}/outbound/{trunk}:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: trunk
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [outbound-voice]
      summary: Request information of specified trunk
      operationId: getOutboundTrunk
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundTrunk'
    put:
      tags: [outbound-voice]
      summary: Create new trunk or update existing trunk
      operationId: putOutboundTrunk
      security:
        - BasicAuth: []
      requestBody:
        description: Trunk to create or update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OutboundTrunk"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundTrunk'
    delete:
      tags: [outbound-voice]
      summary: Delete the trunk
      operationId: deleteOutboundTrunk
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
  /voice/{account}/outbound/{trunk}/acl:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: trunk
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [outbound-voice]
      summary: Request information of specified trunk
      operationId: getOutboundAclIps
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundAclIps'
  /voice/{account}/outbound/{trunk}/acl/{ip}:
    parameters:
      - name: account
        in: path
        required: true
        schema:
          type: string
      - name: trunk
        in: path
        required: true
        schema:
          type: string
      - name: ip
        in: path
        required: true
        schema:
          type: string
    put:
      tags: [outbound-voice]
      summary: Add IP to ACL-based trunk
      operationId: putOutboundAclIp
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
    delete:
      tags: [outbound-voice]
      summary: Remove IP from ACL-based trunk
      operationId: deleteOutboundAclIp
      security:
        - BasicAuth: []
      responses:
        200:
          description: Success
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    MyIp:
      type: object
      required: [ip]
      properties:
        ip:
          type: string
    Time:
      type: object
      required: [api, rfc, timestamp]
      properties:
        api:
          type: string
        rfc:
          type: string
        timestamp:
          type: integer
          format: int32
    AccountTypeResponse:
      type: object
      required: [success, data]
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/AccountType'
    AccountType:
      type: object
      required: [account_type]
      properties:
        account_type:
          type: string
        number_limit:
          type: integer
        channel_limit:
          type: integer
        min_prepay:
          type: integer
    OutboundTrunksResponse:
      type: array
      items:
        $ref: '#/components/schemas/OutboundTrunkSummary'
    OutboundTrunkSummary:
      type: object
      required: [trunk, serviceLevel, type]
      properties:
        trunk:
          type: string
        serviceLevel:
          type: string
        type:
          type: string
        # enabled_webrtc
    OutboundTrunk:
      type: object
      properties:
        trunk:
          type: string
        type:
          type: string
        enabled:
          type: string
        enabled_in:
          type: string
        enabled_out:
          type: string
        # enabled_webrtc
        user:
          type: string
        quality:
          type: string
        limit_concurrent_out:
          type: string
        limit_rate_out:
          type: string
        # limit_concurrent_out_international
        # limit_rate_out_international
        # limit_concurrent_out_international_hotspot
        limit_rate_out_international_hotspot:
          type: string
        # limit_concurrent_out_per_number
        # max_cpc
        # max_cpm
        # max_cost
        # max_dur
        # limit_concurrent_in
        # access_codes_enabled
        # dq_enabled
        # cli_default
        cli_force_default:
          type: string
        # nni_default
        # cli_format
        # cli_policy
    OutboundAclIps:
      type: array
      items:
        $ref: '#/components/schemas/OutboundAclIp'
    OutboundAclIp:
      type: object
      properties:
        ip:
          type: string
        timestamp:
          type: string
